#!/usr/bin/env python3
"""
optimize_memory_safe.py

- Writes/updates `.env.memopt` with safe reduced pool values.
- Creates `monitor_memory_improved.py` and `cleanup_memory_improved.py`.
- Does not modify `backend/database/config.py` directly.
"""

import os
from pathlib import Path
from datetime import datetime

ENV_FILE = Path(".env.memopt")

DEFAULTS = {
    "DB_POOL_SIZE": "10",
    "DB_MAX_OVERFLOW": "15",
    "DB_POOL_TIMEOUT": "20",
    "DB_POOL_PRE_PING": "true",
    "DB_POOL_RECYCLE": "600",
    "DB_CONNECT_COMMAND_TIMEOUT": "10",
}


def write_env_file(path: Path = ENV_FILE, values: dict = DEFAULTS) -> None:
    backup = path.with_suffix(path.suffix + f".bak.{datetime.utcnow().strftime('%Y%m%dT%H%M%SZ')}")
    if path.exists():
        path.replace(backup)
    print(f"Existing env backed up to {backup}")
    lines = [f"# Generated by optimize_memory_safe.py at {datetime.utcnow().isoformat()} (safe tuning)\n"]
    for k, v in values.items():
        lines.append(f"{k}={v}\n")
    path.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote env overrides to {path}")
    print("To apply it, source .env.memopt or load it via your env management tool before running uvicorn.")


def create_monitor() -> None:
    script = r'''#!/usr/bin/env python3
"""
monitor_memory_improved.py
- prints memory + cpu
- prints top N processes by RSS
- supports --interval, --threshold, --top, --log-file
"""
import argparse, time, psutil, logging
from datetime import datetime
from textwrap import shorten

def bytes_to_mib(b): return b/1024/1024

def top_procs(n=8):
    procs=[]
    for p in psutil.process_iter(['pid','name','cmdline','memory_info','cpu_percent']):
        try:
            mem = p.info['memory_info'].rss if p.info.get('memory_info') else 0
            cmd = " ".join(p.info.get('cmdline') or [])
            procs.append((mem, p.pid, p.info.get('name') or '', p.info.get('cpu_percent') or 0, cmd))
        except Exception:
            continue
    procs.sort(reverse=True, key=lambda x: x[0])
    return procs[:n]

def main():
    p=argparse.ArgumentParser()
    p.add_argument("--interval", "-i", type=float, default=30.0)
    p.add_argument("--threshold", "-t", type=float, default=80.0)
    p.add_argument("--top", type=int, default=8)
    p.add_argument("--log-file", default=None)
    args=p.parse_args()
    logger=None
    if args.log_file:
        logging.basicConfig(filename=args.log_file, level=logging.INFO,
                            format="%(asctime)s %(levelname)s %(message)s")
        logger=logging.getLogger()

    print(f"🔍 Memory Monitor Started (threshold: {args.threshold}%)")
    try:
        while True:
            mem=psutil.virtual_memory()
            cpu=psutil.cpu_percent(interval=0.5)
            status = "🔴" if mem.percent>=args.threshold else "🟢"
            print(f"{status} {datetime.now():%H:%M:%S} | Memory: {mem.percent:.1f}% ({mem.used//(1024**3)}GB/{mem.total//(1024**3)}GB) | CPU: {cpu:.1f}%")
            if mem.percent>=args.threshold:
                print("⚠️  WARNING: High memory usage detected!")
                procs=top_procs(args.top)
                print("Top processes by RSS:")
                print(f"{'PID':>6} {'RSS(MB)':>9} {'CPU%':>6} {'Name':<25} Cmdline")
                for mem, pid, name, cpu, cmd in procs:
                    print(f"{pid:>6} {bytes_to_mib(mem):9.1f} {cpu:6.1f} {shorten(name,25)} {shorten(cmd,120)}")
            if logger:
                logger.info({"mem_percent": mem.percent, "used": mem.used, "cpu": cpu})
            time.sleep(args.interval)
    except KeyboardInterrupt:
        print("\n✅ Monitor stopped")

if __name__=="__main__":
    main()
'''
    Path("monitor_memory_improved.py").write_text(script, encoding="utf-8")
    print("monitor_memory_improved.py created")


def create_cleanup() -> None:
    script = r'''#!/usr/bin/env python3
"""
cleanup_memory_improved.py
- recursive __pycache__ removal
- cleanup logs older than N days
- --dry-run option
"""
import argparse, shutil
from pathlib import Path
from datetime import datetime, timedelta

def cleanup_logs(dirpath, days=7, dry=False):
    logs_dir = Path(dirpath)
    if not logs_dir.exists():
        print("logs dir not found:", logs_dir); return 0
    cutoff = datetime.now()-timedelta(days=days)
    removed=0
    for f in logs_dir.rglob("*.log"):
        try:
            if datetime.fromtimestamp(f.stat().st_mtime) < cutoff:
                print("Remove:", f)
                if not dry:
                    f.unlink()
                    removed+=1
        except Exception as e:
            print("Err:",e)
    return removed

def cleanup_pycache(root=".", dry=False):
    removed=0
    for p in Path(root).rglob("__pycache__"):
        print("Remove cache:", p)
        if not dry:
            shutil.rmtree(p)
            removed+=1
    return removed

def cleanup_temp(root=".", dry=False):
    removed=0
    for pattern in ["*.tmp","*.temp","*.cache"]:
        for f in Path(root).rglob(pattern):
            print("Remove temp:", f)
            if not dry:
                try:
                    f.unlink()
                    removed+=1
                except Exception:
                    pass
    return removed

def main():
    p=argparse.ArgumentParser()
    p.add_argument("--logs", default="backend/logs")
    p.add_argument("--days", type=int, default=7)
    p.add_argument("--dry", action="store_true")
    args=p.parse_args()
    print("Dry run:", args.dry)
    r=cleanup_logs(args.logs, args.days, args.dry)
    rc=cleanup_pycache(".", args.dry)
    rt=cleanup_temp(".", args.dry)
    print("Summary removed logs, pycache, temp:", r, rc, rt)

if __name__=="__main__":
    main()
'''
    Path("cleanup_memory_improved.py").write_text(script, encoding="utf-8")
    print("cleanup_memory_improved.py created")


def main() -> int:
    write_env_file()
    create_monitor()
    create_cleanup()
    print("\nNext steps:")
    print("1) Source .env.memopt or load it via your env management tool.")
    print("2) Run monitor: python monitor_memory_improved.py --interval 30 --threshold 80 --top 8")
    print("3) Preview cleanup: python cleanup_memory_improved.py --dry")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
