"""add_tenant_subscription_and_quotas

Revision ID: faab766d1a0f
Revises: c1c4546306e6
Create Date: 2026-01-08 22:24:04.705647

"""

import os
from alembic import context
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.

revision = 'faab766d1a0f'
down_revision = 'c1c4546306e6'
branch_labels = None
depends_on = None

def _destructive_enabled() -> bool:
    # EN upgrade EN
    # EN:
    #   set ALLOW_DESTRUCTIVE_MIGRATIONS=1
    if context.is_offline_mode():
        return False
    return os.getenv("ALLOW_DESTRUCTIVE_MIGRATIONS", "0") == "1"

def _safe_drop_table(*args, **kwargs):
    if _destructive_enabled():
        return _safe_drop_table(*args, **kwargs)
    return None

def _safe_drop_index(*args, **kwargs):
    if _destructive_enabled():
        return _safe_drop_index(*args, **kwargs)
    return None

def _safe_drop_column(*args, **kwargs):
    if _destructive_enabled():
        return _safe_drop_column(*args, **kwargs)
    return None

def _safe_drop_constraint(*args, **kwargs):
    if _destructive_enabled():
        return _safe_drop_constraint(*args, **kwargs)
    return None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_tracking_id', sa.String(), nullable=False),
    sa.Column('shipment_reference', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('created', 'picked_up', 'in_transit', 'delayed', 'delivered', 'cancelled', name='shipment_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('shipper_id', sa.Integer(), nullable=True),
    sa.Column('consignee_id', sa.Integer(), nullable=True),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tracking_shipments_carrier_status', 'tracking_shipments', ['carrier_id', 'status'], unique=False)
    op.create_index('idx_tracking_shipments_status_date', 'tracking_shipments', ['status', 'created_at'], unique=False)
    op.create_index('idx_tracking_shipments_tracking_reference', 'tracking_shipments', ['external_tracking_id', 'shipment_reference'], unique=False)
    op.create_index(op.f('ix_tracking_shipments_broker_id'), 'tracking_shipments', ['broker_id'], unique=False)
    op.create_index(op.f('ix_tracking_shipments_carrier_id'), 'tracking_shipments', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_tracking_shipments_consignee_id'), 'tracking_shipments', ['consignee_id'], unique=False)
    op.create_index(op.f('ix_tracking_shipments_created_at'), 'tracking_shipments', ['created_at'], unique=False)
    op.create_index(op.f('ix_tracking_shipments_external_tracking_id'), 'tracking_shipments', ['external_tracking_id'], unique=True)
    op.create_index(op.f('ix_tracking_shipments_id'), 'tracking_shipments', ['id'], unique=False)
    op.create_index(op.f('ix_tracking_shipments_invoice_id'), 'tracking_shipments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_tracking_shipments_shipment_reference'), 'tracking_shipments', ['shipment_reference'], unique=False)
    op.create_index(op.f('ix_tracking_shipments_shipper_id'), 'tracking_shipments', ['shipper_id'], unique=False)
    op.create_index(op.f('ix_tracking_shipments_status'), 'tracking_shipments', ['status'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhook_client_time', 'webhook_logs', ['client_id', 'received_at'], unique=False)
    op.create_index('idx_webhook_processed_status', 'webhook_logs', ['processed', 'response_status'], unique=False)
    op.create_index(op.f('ix_webhook_logs_client_id'), 'webhook_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_idempotency_key'), 'webhook_logs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_webhook_logs_processed'), 'webhook_logs', ['processed'], unique=False)
    op.create_index(op.f('ix_webhook_logs_received_at'), 'webhook_logs', ['received_at'], unique=False)
    op.create_table('tracking_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('created', 'picked_up', 'in_transit', 'delayed', 'delivered', 'cancelled', name='shipment_status_enum'), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('webhook_received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['tracking_shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tracking_events_processed_time', 'tracking_events', ['processed', 'webhook_received_at'], unique=False)
    op.create_index('idx_tracking_events_shipment_time', 'tracking_events', ['shipment_id', 'event_time'], unique=False)
    op.create_index(op.f('ix_tracking_events_event_time'), 'tracking_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_tracking_events_event_type'), 'tracking_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_tracking_events_id'), 'tracking_events', ['id'], unique=False)
    op.create_index(op.f('ix_tracking_events_processed'), 'tracking_events', ['processed'], unique=False)
    op.create_index(op.f('ix_tracking_events_shipment_id'), 'tracking_events', ['shipment_id'], unique=False)
    op.create_table('tracking_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('issue_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending', 'sent', 'paid', 'overdue', 'cancelled', name='invoice_status_enum'), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['tracking_shipments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tracking_invoice_carrier', 'tracking_invoices', ['carrier_id', 'status'], unique=False)
    op.create_index('idx_tracking_invoice_customer_date', 'tracking_invoices', ['customer_id', 'issue_date'], unique=False)
    op.create_index('idx_tracking_invoice_status_due', 'tracking_invoices', ['status', 'due_date'], unique=False)
    op.create_index(op.f('ix_tracking_invoices_carrier_id'), 'tracking_invoices', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_tracking_invoices_customer_id'), 'tracking_invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_tracking_invoices_due_date'), 'tracking_invoices', ['due_date'], unique=False)
    op.create_index(op.f('ix_tracking_invoices_id'), 'tracking_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_tracking_invoices_invoice_number'), 'tracking_invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_tracking_invoices_shipment_id'), 'tracking_invoices', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_tracking_invoices_status'), 'tracking_invoices', ['status'], unique=False)
    _safe_drop_index(op.f('idx_partner_payouts_partner'), table_name='partner_payouts')
    _safe_drop_index(op.f('idx_partner_payouts_status'), table_name='partner_payouts')
    _safe_drop_table('partner_payouts')
    _safe_drop_index(op.f('ix_org_memberships_org_unit_id'), table_name='org_memberships')
    _safe_drop_index(op.f('ix_org_memberships_user_id'), table_name='org_memberships')
    _safe_drop_table('org_memberships')
    _safe_drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    _safe_drop_index(op.f('ix_refresh_tokens_user_active'), table_name='refresh_tokens')
    _safe_drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    _safe_drop_table('refresh_tokens')
    _safe_drop_table('role_permissions')
    _safe_drop_index(op.f('idx_email_threads_last_message'), table_name='email_threads')
    _safe_drop_index(op.f('idx_email_threads_mailbox_id'), table_name='email_threads')
    _safe_drop_index(op.f('ix_email_threads_created_at'), table_name='email_threads')
    _safe_drop_index(op.f('ix_email_threads_mailbox_id'), table_name='email_threads')
    _safe_drop_table('email_threads')
    _safe_drop_index(op.f('ix_permissions_scope'), table_name='permissions')
    _safe_drop_table('permissions')
    _safe_drop_index(op.f('ix_roles_parent_role_id'), table_name='roles')
    _safe_drop_table('roles')
    _safe_drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    _safe_drop_index(op.f('ix_email_logs_recipient_email'), table_name='email_logs')
    _safe_drop_table('email_logs')
    _safe_drop_index(op.f('ix_mailbox_requests_created_at'), table_name='mailbox_requests')
    _safe_drop_index(op.f('ix_mailbox_requests_requester'), table_name='mailbox_requests')
    _safe_drop_index(op.f('ix_mailbox_requests_status'), table_name='mailbox_requests')
    _safe_drop_table('mailbox_requests')
    _safe_drop_index(op.f('idx_email_mailbox_users_mailbox_id'), table_name='email_mailbox_users')
    _safe_drop_index(op.f('idx_email_mailbox_users_user_id'), table_name='email_mailbox_users')
    _safe_drop_table('email_mailbox_users')
    _safe_drop_index(op.f('ix_financial_summaries_id'), table_name='financial_summaries')
    _safe_drop_table('financial_summaries')
    _safe_drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    _safe_drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    _safe_drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    _safe_drop_index(op.f('ix_audit_logs_severity'), table_name='audit_logs')
    _safe_drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    _safe_drop_table('audit_logs')
    _safe_drop_index(op.f('idx_portal_access_requests_created_at'), table_name='portal_access_requests')
    _safe_drop_index(op.f('idx_portal_access_requests_email'), table_name='portal_access_requests')
    _safe_drop_index(op.f('idx_portal_access_requests_status'), table_name='portal_access_requests')
    _safe_drop_table('portal_access_requests')
    _safe_drop_index(op.f('ix_users_id'), table_name='users')
    _safe_drop_index(op.f('ix_users_manager_id'), table_name='users')
    _safe_drop_table('users')
    _safe_drop_index(op.f('ix_email_attachments_message_id'), table_name='email_attachments')
    _safe_drop_table('email_attachments')
    _safe_drop_index(op.f('ix_shipments_id'), table_name='shipments')
    _safe_drop_table('shipments')
    _safe_drop_table('mailbox_credentials')
    _safe_drop_index(op.f('idx_expenses_category'), table_name='expenses')
    _safe_drop_index(op.f('idx_expenses_created'), table_name='expenses')
    _safe_drop_index(op.f('idx_expenses_status'), table_name='expenses')
    _safe_drop_index(op.f('idx_expenses_vendor'), table_name='expenses')
    _safe_drop_index(op.f('ix_expenses_id'), table_name='expenses')
    _safe_drop_index(op.f('uq_expenses_dedupe'), table_name='expenses', postgresql_where='(dedupe_key IS NOT NULL)')
    _safe_drop_table('expenses')
    _safe_drop_index(op.f('ix_shipments_mvp_created_at'), table_name='shipments_mvp')
    _safe_drop_index(op.f('ix_shipments_mvp_created_at_status'), table_name='shipments_mvp')
    _safe_drop_index(op.f('ix_shipments_mvp_status'), table_name='shipments_mvp')
    _safe_drop_table('shipments_mvp')
    _safe_drop_table('email_mailboxes')
    _safe_drop_index(op.f('ix_user_roles_org_unit_id'), table_name='user_roles')
    _safe_drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    _safe_drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    _safe_drop_table('user_roles')
    _safe_drop_table('bot_identities')
    _safe_drop_index(op.f('idx_shipment_events_created_at'), table_name='shipment_events')
    _safe_drop_index(op.f('idx_shipment_events_shipment_id'), table_name='shipment_events')
    _safe_drop_table('shipment_events')
    _safe_drop_index(op.f('ix_email_audit_logs_action'), table_name='email_audit_logs')
    _safe_drop_index(op.f('ix_email_audit_logs_actor_user_id'), table_name='email_audit_logs')
    _safe_drop_index(op.f('ix_email_audit_logs_created_at'), table_name='email_audit_logs')
    _safe_drop_table('email_audit_logs')
    _safe_drop_index(op.f('idx_partner_agreements_active'), table_name='partner_agreements')
    _safe_drop_index(op.f('idx_partner_agreements_partner'), table_name='partner_agreements')
    _safe_drop_table('partner_agreements')
    _safe_drop_table('template_permissions')
    _safe_drop_index(op.f('idx_documents_expires_at'), table_name='documents')
    _safe_drop_table('documents')
    _safe_drop_index(op.f('ix_message_logs_id'), table_name='message_logs')
    _safe_drop_table('message_logs')
    _safe_drop_index(op.f('idx_partner_revenue_partner'), table_name='partner_revenue')
    _safe_drop_index(op.f('idx_partner_revenue_period'), table_name='partner_revenue')
    _safe_drop_index(op.f('idx_partner_revenue_status'), table_name='partner_revenue')
    _safe_drop_table('partner_revenue')
    _safe_drop_index(op.f('ix_alert_rules_created_at'), table_name='alert_rules')
    _safe_drop_index(op.f('ix_alert_rules_is_enabled'), table_name='alert_rules')
    _safe_drop_index(op.f('ix_alert_rules_severity'), table_name='alert_rules')
    _safe_drop_table('alert_rules')
    _safe_drop_index(op.f('idx_email_mailbox_roles_mailbox_id'), table_name='email_mailbox_roles')
    _safe_drop_index(op.f('idx_email_mailbox_roles_role'), table_name='email_mailbox_roles')
    _safe_drop_table('email_mailbox_roles')
    _safe_drop_index(op.f('ix_ai_bot_issues_id'), table_name='ai_bot_issues')
    _safe_drop_table('ai_bot_issues')
    _safe_drop_table('platform_expenses')
    _safe_drop_table('permission_templates')
    _safe_drop_index(op.f('idx_bot_audit_events_bot_name'), table_name='bot_audit_events')
    _safe_drop_table('bot_audit_events')
    _safe_drop_index(op.f('ix_org_units_created_at'), table_name='org_units')
    _safe_drop_index(op.f('ix_org_units_parent_id'), table_name='org_units')
    _safe_drop_table('org_units')
    _safe_drop_index(op.f('ix_sessions_created_at'), table_name='sessions')
    _safe_drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    _safe_drop_table('sessions')
    _safe_drop_table('monthly_reports')
    _safe_drop_index(op.f('idx_partners_joined_at'), table_name='partners')
    _safe_drop_index(op.f('idx_partners_status'), table_name='partners')
    _safe_drop_index(op.f('ix_partners_status'), table_name='partners')
    _safe_drop_index(op.f('ix_partners_tier'), table_name='partners')
    _safe_drop_table('partners')
    _safe_drop_index(op.f('ix_mailboxes_bot_code'), table_name='mailboxes')
    _safe_drop_index(op.f('ix_mailboxes_enabled'), table_name='mailboxes')
    _safe_drop_index(op.f('ix_mailboxes_owner_user_id'), table_name='mailboxes')
    _safe_drop_table('mailboxes')
    _safe_drop_index(op.f('idx_email_messages_created_at'), table_name='email_messages')
    _safe_drop_index(op.f('idx_email_messages_mailbox_id'), table_name='email_messages')
    _safe_drop_index(op.f('idx_email_messages_thread_id'), table_name='email_messages')
    _safe_drop_index(op.f('ix_email_messages_created_at'), table_name='email_messages')
    _safe_drop_index(op.f('ix_email_messages_mailbox_id'), table_name='email_messages')
    _safe_drop_index(op.f('ix_email_messages_status'), table_name='email_messages')
    _safe_drop_table('email_messages')
    _safe_drop_index(op.f('idx_partner_clients_client'), table_name='partner_clients')
    _safe_drop_index(op.f('idx_partner_clients_partner'), table_name='partner_clients')
    _safe_drop_table('partner_clients')
    op.alter_column('governance_approvals', 'decision',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('governance_bots', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('governance_bots', 'approvals_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    _safe_drop_index(op.f('ix_human_commands_created_at_desc'), table_name='human_commands')
    op.add_column('invoices', sa.Column('shipment_id', sa.Integer(), nullable=True))
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    _safe_drop_index(op.f('ix_invoices_id'), table_name='invoices')
    _safe_drop_index(op.f('ix_invoices_number'), table_name='invoices')
    op.alter_column('open_web_leads', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_open_web_leads_status'), 'open_web_leads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _safe_drop_index(op.f('ix_open_web_leads_status'), table_name='open_web_leads')
    op.alter_column('open_web_leads', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'new'::character varying"),
               existing_nullable=False)
    op.create_index(op.f('ix_invoices_number'), 'invoices', ['number'], unique=True)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    _safe_drop_column('invoices', 'shipment_id')
    op.create_index(op.f('ix_human_commands_created_at_desc'), 'human_commands', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('governance_bots', 'approvals_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('governance_bots', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'under_review'::character varying"),
               existing_nullable=False)
    op.alter_column('governance_approvals', 'decision',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'approved'::character varying"),
               existing_nullable=False)
    op.create_table('partner_clients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('partner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('relationship_started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('relationship_channel', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('partner_clients_partner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('partner_clients_pkey')),
    sa.UniqueConstraint('partner_id', 'client_id', name=op.f('partner_clients_partner_id_client_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_partner_clients_partner'), 'partner_clients', ['partner_id'], unique=False)
    op.create_index(op.f('idx_partner_clients_client'), 'partner_clients', ['client_id'], unique=False)
    op.create_table('email_messages',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('email_messages_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mailbox_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=16), server_default=sa.text("'inbound'::character varying"), autoincrement=False, nullable=False),
    sa.Column('from_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('to_emails', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('body_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body_html', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('in_reply_to', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False),
    sa.Column('requires_approval', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('approved_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('imap_uid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('from_addr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('to_addrs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('cc_addrs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('body_preview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body_storage_ref', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assigned_bot', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('workflow_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_headers_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('classifier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('class_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detected_category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ai_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name='email_messages_approved_by_user_id_fkey'),
    sa.ForeignKeyConstraint(['mailbox_id'], ['email_mailboxes.id'], name='email_messages_mailbox_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], name='fk_email_messages_mailbox_id_mailboxes', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['email_threads.id'], name='email_messages_thread_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['email_threads.id'], name='fk_email_messages_thread_id_email_threads'),
    sa.PrimaryKeyConstraint('id', name='email_messages_pkey'),
    sa.UniqueConstraint('mailbox_id', 'imap_uid', name='uq_email_messages_mailbox_imap_uid', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_email_messages_status'), 'email_messages', ['status'], unique=False)
    op.create_index(op.f('ix_email_messages_mailbox_id'), 'email_messages', ['mailbox_id'], unique=False)
    op.create_index(op.f('ix_email_messages_created_at'), 'email_messages', ['created_at'], unique=False)
    op.create_index(op.f('idx_email_messages_thread_id'), 'email_messages', ['thread_id'], unique=False)
    op.create_index(op.f('idx_email_messages_mailbox_id'), 'email_messages', ['mailbox_id'], unique=False)
    op.create_index(op.f('idx_email_messages_created_at'), 'email_messages', ['created_at'], unique=False)
    op.create_table('mailboxes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('mailboxes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bot_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mode', sa.VARCHAR(length=20), server_default=sa.text("'HUMAN'::character varying"), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=30), server_default=sa.text("'INBOUND_OUTBOUND'::character varying"), autoincrement=False, nullable=False),
    sa.Column('imap_host', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('imap_port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('imap_user', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('imap_ssl', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('smtp_host', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('smtp_port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('smtp_user', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('smtp_ssl', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('use_tls', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('inbound_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('outbound_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('polling_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('auto_reply_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('package_scope', sa.VARCHAR(length=20), server_default=sa.text("'SYSTEM'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_polled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_uid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_message_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name='mailboxes_owner_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='mailboxes_pkey'),
    sa.UniqueConstraint('tenant_id', 'email_address', name='uq_mailboxes_tenant_email', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_mailboxes_owner_user_id'), 'mailboxes', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_mailboxes_enabled'), 'mailboxes', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_mailboxes_bot_code'), 'mailboxes', ['bot_code'], unique=False)
    op.create_table('partners',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('partner_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('address_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bank_account_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bank_account_iban', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('bank_account_swift', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('bank_details_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('default_b2b_share', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('60.00'), autoincrement=False, nullable=False),
    sa.Column('default_b2c_share', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('70.00'), autoincrement=False, nullable=False),
    sa.Column('default_marketplace_share', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('80.00'), autoincrement=False, nullable=False),
    sa.Column('revenue_total', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('revenue_pending', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('revenue_paid', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('referral_link_slug', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('referral_code', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('tier', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='partners_pkey'),
    sa.UniqueConstraint('code', name='partners_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('email', name='partners_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('referral_code', name='partners_referral_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('referral_link_slug', name='partners_referral_link_slug_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_partners_tier'), 'partners', ['tier'], unique=False)
    op.create_index(op.f('ix_partners_status'), 'partners', ['status'], unique=False)
    op.create_index(op.f('idx_partners_status'), 'partners', ['status'], unique=False)
    op.create_index(op.f('idx_partners_joined_at'), 'partners', ['joined_at'], unique=False)
    op.create_table('monthly_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('month', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('expenses', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('monthly_reports_pkey')),
    sa.UniqueConstraint('month', name=op.f('monthly_reports_month_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ip', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sessions_pkey'))
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_created_at'), 'sessions', ['created_at'], unique=False)
    op.create_table('org_units',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('org_units_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['org_units.id'], name='org_units_parent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='org_units_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_org_units_parent_id'), 'org_units', ['parent_id'], unique=False)
    op.create_index(op.f('ix_org_units_created_at'), 'org_units', ['created_at'], unique=False)
    op.create_table('bot_audit_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bot_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('bot_audit_events_pkey'))
    )
    op.create_index(op.f('idx_bot_audit_events_bot_name'), 'bot_audit_events', ['bot_name'], unique=False)
    op.create_table('permission_templates',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('permission_templates_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='permission_templates_pkey'),
    sa.UniqueConstraint('name', name='permission_templates_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('platform_expenses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vendor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('currency', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('incurred_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('platform_expenses_pkey'))
    )
    op.create_table('ai_bot_issues',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bot_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('issue_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resolved', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_bot_issues_pkey'))
    )
    op.create_index(op.f('ix_ai_bot_issues_id'), 'ai_bot_issues', ['id'], unique=False)
    op.create_table('email_mailbox_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mailbox_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('can_read', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('can_send', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('can_manage', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['email_mailboxes.id'], name=op.f('email_mailbox_roles_mailbox_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('email_mailbox_roles_pkey'))
    )
    op.create_index(op.f('idx_email_mailbox_roles_role'), 'email_mailbox_roles', ['role_name'], unique=False)
    op.create_index(op.f('idx_email_mailbox_roles_mailbox_id'), 'email_mailbox_roles', ['mailbox_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('condition_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('channels_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_rules_pkey'))
    )
    op.create_index(op.f('ix_alert_rules_severity'), 'alert_rules', ['severity'], unique=False)
    op.create_index(op.f('ix_alert_rules_is_enabled'), 'alert_rules', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_alert_rules_created_at'), 'alert_rules', ['created_at'], unique=False)
    op.create_table('partner_revenue',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('partner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('service_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('currency_code', sa.VARCHAR(length=3), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=False),
    sa.Column('gross_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('net_profit_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('partner_share_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('partner_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('gts_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('period_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period_month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('partner_revenue_partner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('partner_revenue_pkey')),
    sa.UniqueConstraint('order_id', name=op.f('partner_revenue_order_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_partner_revenue_status'), 'partner_revenue', ['status'], unique=False)
    op.create_index(op.f('idx_partner_revenue_period'), 'partner_revenue', ['period_year', 'period_month'], unique=False)
    op.create_index(op.f('idx_partner_revenue_partner'), 'partner_revenue', ['partner_id'], unique=False)
    op.create_table('message_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('context', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('message_logs_pkey'))
    )
    op.create_index(op.f('ix_message_logs_id'), 'message_logs', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notify_before_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('valid', 'expiring', 'expired', name='document_status'), server_default=sa.text("'valid'::document_status"), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    op.create_index(op.f('idx_documents_expires_at'), 'documents', ['expires_at'], unique=False)
    op.create_table('template_permissions',
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('template_permissions_permission_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['permission_templates.id'], name=op.f('template_permissions_template_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id', 'permission_id', name=op.f('template_permissions_pkey'))
    )
    op.create_table('partner_agreements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('partner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agreement_version', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('agreement_text_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('signed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('signature_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('signature_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('pdf_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('partner_agreements_partner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('partner_agreements_pkey'))
    )
    op.create_index(op.f('idx_partner_agreements_partner'), 'partner_agreements', ['partner_id'], unique=False)
    op.create_index(op.f('idx_partner_agreements_active'), 'partner_agreements', ['partner_id', 'is_active'], unique=False)
    op.create_table('email_audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('mailbox_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('diff_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('email_audit_logs_actor_user_id_fkey')),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], name=op.f('email_audit_logs_mailbox_id_fkey')),
    sa.ForeignKeyConstraint(['message_id'], ['email_messages.id'], name=op.f('email_audit_logs_message_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('email_audit_logs_pkey'))
    )
    op.create_index(op.f('ix_email_audit_logs_created_at'), 'email_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_audit_logs_actor_user_id'), 'email_audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_email_audit_logs_action'), 'email_audit_logs', ['action'], unique=False)
    op.create_table('shipment_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('actor_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('shipment_events_pkey'))
    )
    op.create_index(op.f('idx_shipment_events_shipment_id'), 'shipment_events', ['shipment_id'], unique=False)
    op.create_index(op.f('idx_shipment_events_created_at'), 'shipment_events', ['created_at'], unique=False)
    op.create_table('bot_identities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bot_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('inbox_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sender_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('allowed_actions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('default_mode', sa.VARCHAR(length=32), server_default=sa.text("'BOT'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('bot_identities_pkey')),
    sa.UniqueConstraint('bot_name', name=op.f('bot_identities_bot_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_units.id'], name=op.f('user_roles_org_unit_id_fkey')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('user_roles_role_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_roles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('user_roles_pkey'))
    )
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_org_unit_id'), 'user_roles', ['org_unit_id'], unique=False)
    op.create_table('email_mailboxes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('email_mailboxes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bot_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('mode', sa.VARCHAR(length=32), server_default=sa.text("'BOT'::character varying"), autoincrement=False, nullable=False),
    sa.Column('inbound_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('outbound_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('imap_host', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('imap_port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('imap_user', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('imap_password_enc', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('imap_ssl', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('smtp_host', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('smtp_port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('smtp_user', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('smtp_password_enc', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('smtp_ssl', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name='email_mailboxes_owner_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='email_mailboxes_pkey'),
    sa.UniqueConstraint('email_address', name='email_mailboxes_email_address_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('shipments_mvp',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('origin', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('destination', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('shipments_mvp_pkey'))
    )
    op.create_index(op.f('ix_shipments_mvp_status'), 'shipments_mvp', ['status'], unique=False)
    op.create_index(op.f('ix_shipments_mvp_created_at_status'), 'shipments_mvp', ['created_at', 'status'], unique=False)
    op.create_index(op.f('ix_shipments_mvp_created_at'), 'shipments_mvp', ['created_at'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), server_default=sa.text("'misc'::character varying"), autoincrement=False, nullable=False),
    sa.Column('vendor', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('dedupe_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("status = ANY (ARRAY['PENDING'::text, 'PAID'::text])", name=op.f('ck_expenses_ck_expenses_status')),
    sa.CheckConstraint("status = ANY (ARRAY['PENDING'::text, 'PAID'::text])", name=op.f('ck_expenses_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('expenses_pkey'))
    )
    op.create_index(op.f('uq_expenses_dedupe'), 'expenses', ['dedupe_key'], unique=True, postgresql_where='(dedupe_key IS NOT NULL)')
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('idx_expenses_vendor'), 'expenses', ['vendor'], unique=False)
    op.create_index(op.f('idx_expenses_status'), 'expenses', ['status'], unique=False)
    op.create_index(op.f('idx_expenses_created'), 'expenses', ['created_at'], unique=False)
    op.create_index(op.f('idx_expenses_category'), 'expenses', ['category'], unique=False)
    op.create_table('mailbox_credentials',
    sa.Column('mailbox_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('credentials_ciphertext', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('rotated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], name=op.f('mailbox_credentials_mailbox_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mailbox_id', name=op.f('mailbox_credentials_pkey'))
    )
    op.create_table('shipments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pickup_location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dropoff_location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trailer_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recurring_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('days', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('load_size', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('length', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('distance_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('duration_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('price_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dropoff_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dropoff_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('shipments_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shipments_pkey'))
    )
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    op.create_table('email_attachments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('storage_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('storage_ref', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detected_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['email_messages.id'], name=op.f('email_attachments_message_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['email_messages.id'], name=op.f('fk_email_attachments_message_id_email_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('email_attachments_pkey'))
    )
    op.create_index(op.f('ix_email_attachments_message_id'), 'email_attachments', ['message_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_banned', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ban_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('banned_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name='users_manager_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name='users_username_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_users_manager_id'), 'users', ['manager_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('portal_access_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('mobile', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('us_state', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('dot_number', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('mc_number', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('us_business_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ca_province', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('ca_registered_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ca_company_number', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('document_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('rejected_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rejected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('portal_access_requests_pkey'))
    )
    op.create_index(op.f('idx_portal_access_requests_status'), 'portal_access_requests', ['status'], unique=False)
    op.create_index(op.f('idx_portal_access_requests_email'), 'portal_access_requests', ['email'], unique=False)
    op.create_index(op.f('idx_portal_access_requests_created_at'), 'portal_access_requests', ['created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('target_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('diff_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('audit_logs_actor_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_severity'), 'audit_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('financial_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('total_expenses', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('period', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('financial_summaries_pkey'))
    )
    op.create_index(op.f('ix_financial_summaries_id'), 'financial_summaries', ['id'], unique=False)
    op.create_table('email_mailbox_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mailbox_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('can_read', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('can_send', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('can_manage', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['email_mailboxes.id'], name=op.f('email_mailbox_users_mailbox_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('email_mailbox_users_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('email_mailbox_users_pkey'))
    )
    op.create_index(op.f('idx_email_mailbox_users_user_id'), 'email_mailbox_users', ['user_id'], unique=False)
    op.create_index(op.f('idx_email_mailbox_users_mailbox_id'), 'email_mailbox_users', ['mailbox_id'], unique=False)
    op.create_table('mailbox_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('requester_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requested_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('desired_mode', sa.VARCHAR(length=20), server_default=sa.text("'HUMAN'::character varying"), autoincrement=False, nullable=False),
    sa.Column('package_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('decided_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('mailbox_requests_approved_by_fkey')),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], name=op.f('mailbox_requests_requester_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('mailbox_requests_pkey'))
    )
    op.create_index(op.f('ix_mailbox_requests_status'), 'mailbox_requests', ['status'], unique=False)
    op.create_index(op.f('ix_mailbox_requests_requester'), 'mailbox_requests', ['requester_user_id'], unique=False)
    op.create_index(op.f('ix_mailbox_requests_created_at'), 'mailbox_requests', ['created_at'], unique=False)
    op.create_table('email_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recipient_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('template_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_test', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_logs'))
    )
    op.create_index(op.f('ix_email_logs_recipient_email'), 'email_logs', ['recipient_email'], unique=False)
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('roles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_role_id'], ['roles.id'], name='roles_parent_role_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    sa.UniqueConstraint('name', name='roles_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_roles_parent_role_id'), 'roles', ['parent_role_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('permissions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scope_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('scope_key', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='permissions_pkey'),
    sa.UniqueConstraint('code', name='permissions_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_permissions_scope'), 'permissions', ['scope_type', 'scope_key'], unique=False)
    op.create_table('email_threads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mailbox_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False),
    sa.Column('assigned_to_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('last_message_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], name=op.f('email_threads_assigned_to_user_id_fkey')),
    sa.ForeignKeyConstraint(['mailbox_id'], ['email_mailboxes.id'], name=op.f('email_threads_mailbox_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], name=op.f('fk_email_threads_mailbox_id_mailboxes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('email_threads_pkey'))
    )
    op.create_index(op.f('ix_email_threads_mailbox_id'), 'email_threads', ['mailbox_id'], unique=False)
    op.create_index(op.f('ix_email_threads_created_at'), 'email_threads', ['created_at'], unique=False)
    op.create_index(op.f('idx_email_threads_mailbox_id'), 'email_threads', ['mailbox_id'], unique=False)
    op.create_index(op.f('idx_email_threads_last_message'), 'email_threads', ['last_message_at'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('role_permissions_permission_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('role_permissions_role_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('role_permissions_pkey'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('replaced_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], name=op.f('refresh_tokens_replaced_by_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('refresh_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_active'), 'refresh_tokens', ['user_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('org_memberships',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_unit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_units.id'], name=op.f('org_memberships_org_unit_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('org_memberships_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'org_unit_id', name=op.f('org_memberships_pkey'))
    )
    op.create_index(op.f('ix_org_memberships_user_id'), 'org_memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_org_memberships_org_unit_id'), 'org_memberships', ['org_unit_id'], unique=False)
    op.create_table('partner_payouts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('partner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('currency_code', sa.VARCHAR(length=3), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('fees_amount', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('net_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('period_start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('period_end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'requested'::character varying"), autoincrement=False, nullable=False),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('rejected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('payment_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('partner_payouts_partner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('partner_payouts_pkey'))
    )
    op.create_index(op.f('idx_partner_payouts_status'), 'partner_payouts', ['status'], unique=False)
    op.create_index(op.f('idx_partner_payouts_partner'), 'partner_payouts', ['partner_id'], unique=False)
    _safe_drop_index(op.f('ix_tracking_invoices_status'), table_name='tracking_invoices')
    _safe_drop_index(op.f('ix_tracking_invoices_shipment_id'), table_name='tracking_invoices')
    _safe_drop_index(op.f('ix_tracking_invoices_invoice_number'), table_name='tracking_invoices')
    _safe_drop_index(op.f('ix_tracking_invoices_id'), table_name='tracking_invoices')
    _safe_drop_index(op.f('ix_tracking_invoices_due_date'), table_name='tracking_invoices')
    _safe_drop_index(op.f('ix_tracking_invoices_customer_id'), table_name='tracking_invoices')
    _safe_drop_index(op.f('ix_tracking_invoices_carrier_id'), table_name='tracking_invoices')
    _safe_drop_index('idx_tracking_invoice_status_due', table_name='tracking_invoices')
    _safe_drop_index('idx_tracking_invoice_customer_date', table_name='tracking_invoices')
    _safe_drop_index('idx_tracking_invoice_carrier', table_name='tracking_invoices')
    _safe_drop_table('tracking_invoices')
    _safe_drop_index(op.f('ix_tracking_events_shipment_id'), table_name='tracking_events')
    _safe_drop_index(op.f('ix_tracking_events_processed'), table_name='tracking_events')
    _safe_drop_index(op.f('ix_tracking_events_id'), table_name='tracking_events')
    _safe_drop_index(op.f('ix_tracking_events_event_type'), table_name='tracking_events')
    _safe_drop_index(op.f('ix_tracking_events_event_time'), table_name='tracking_events')
    _safe_drop_index('idx_tracking_events_shipment_time', table_name='tracking_events')
    _safe_drop_index('idx_tracking_events_processed_time', table_name='tracking_events')
    _safe_drop_table('tracking_events')
    _safe_drop_index(op.f('ix_webhook_logs_received_at'), table_name='webhook_logs')
    _safe_drop_index(op.f('ix_webhook_logs_processed'), table_name='webhook_logs')
    _safe_drop_index(op.f('ix_webhook_logs_idempotency_key'), table_name='webhook_logs')
    _safe_drop_index(op.f('ix_webhook_logs_client_id'), table_name='webhook_logs')
    _safe_drop_index('idx_webhook_processed_status', table_name='webhook_logs')
    _safe_drop_index('idx_webhook_client_time', table_name='webhook_logs')
    _safe_drop_table('webhook_logs')
    _safe_drop_index(op.f('ix_tracking_shipments_status'), table_name='tracking_shipments')
    _safe_drop_index(op.f('ix_tracking_shipments_shipper_id'), table_name='tracking_shipments')
    _safe_drop_index(op.f('ix_tracking_shipments_shipment_reference'), table_name='tracking_shipments')
    _safe_drop_index(op.f('ix_tracking_shipments_invoice_id'), table_name='tracking_shipments')
    _safe_drop_index(op.f('ix_tracking_shipments_id'), table_name='tracking_shipments')
    _safe_drop_index(op.f('ix_tracking_shipments_external_tracking_id'), table_name='tracking_shipments')
    _safe_drop_index(op.f('ix_tracking_shipments_created_at'), table_name='tracking_shipments')
    _safe_drop_index(op.f('ix_tracking_shipments_consignee_id'), table_name='tracking_shipments')
    _safe_drop_index(op.f('ix_tracking_shipments_carrier_id'), table_name='tracking_shipments')
    _safe_drop_index(op.f('ix_tracking_shipments_broker_id'), table_name='tracking_shipments')
    _safe_drop_index('idx_tracking_shipments_tracking_reference', table_name='tracking_shipments')
    _safe_drop_index('idx_tracking_shipments_status_date', table_name='tracking_shipments')
    _safe_drop_index('idx_tracking_shipments_carrier_status', table_name='tracking_shipments')
    _safe_drop_table('tracking_shipments')
    # ### end Alembic commands ###
