export const TIER_ORDER = [
  "Basic",
  "Growth",
  "Professional",
  "Enterprise",
  "Marketing",
  "Management",
  "Training",
];

export const BOTS_REGISTRY = [
  {
    id: 1,
    key: "customer_service",
    name: "AI Customer Service",
    description: "Automated customer support, notifications, and feedback analysis",
    icon: "💬",
    path: "/ai-bots/customer-service",
    tier: "Basic",
    category: "support",
    status: "active",
    phase: "starter",
    order: 1,
    features: ["Ticket Management", "Chat Support", "Feedback Analysis", "Notifications"],
  },
  {
    id: 2,
    key: "documents_manager",
    name: "AI Documents Manager",
    description: "Document archiving, compliance workflows, and file control",
    icon: "📄",
    path: "/ai-bots/documents",
    tier: "Basic",
    category: "documents",
    status: "active",
    phase: "starter",
    order: 2,
    features: ["OCR", "Archiving", "Compliance", "Version Control"],
  },
  {
    id: 3,
    key: "ai_dispatcher",
    name: "AI Dispatcher",
    description: "Real-time dispatch management and task distribution",
    icon: "🚛",
    path: "/ai-bots/aid-dispatcher",
    tier: "Growth",
    category: "operations",
    status: "active",
    phase: "growth",
    order: 3,
    features: ["Task Routing", "Dispatch Queue", "Real-time Tracking", "Automation"],
    aliases: ["dispatcher"],
  },
  {
    id: 4,
    key: "operations_manager_bot",
    name: "AI Operations Manager",
    description: "Coordinates daily operations and workflow orchestration",
    icon: "⚙️",
    path: "/ai-bots/operations",
    tier: "Growth",
    category: "operations",
    status: "active",
    phase: "growth",
    order: 4,
    features: ["Workflow", "Escalations", "Scheduling", "Monitoring"],
    aliases: ["operations_manager", "operations_bot"],
  },
  {
    id: 5,
    key: "information_coordinator",
    name: "AI Information Coordinator",
    description: "Routes intelligence and connects data to operations",
    icon: "🔄",
    path: "/ai-bots/information",
    tier: "Growth",
    category: "intelligence",
    status: "active",
    phase: "growth",
    order: 5,
    features: ["Data Routing", "Knowledge Base", "Signals", "Briefings"],
    aliases: ["information", "info"],
  },
  {
    id: 6,
    key: "sales_bot",
    name: "AI Sales Bot",
    description: "CRM insights, lead management, and revenue analysis",
    icon: "💰",
    path: "/ai-bots/sales",
    tier: "Growth",
    category: "sales",
    status: "active",
    phase: "growth",
    order: 6,
    features: ["Pipeline", "Leads", "Forecasts", "Insights"],
    aliases: ["sales_team"],
  },
  {
    id: 7,
    key: "freight_broker",
    name: "AI Freight Broker",
    description: "Handles freight brokerage, shipment creation, and dispatch workflows",
    icon: "FRT",
    path: "/ai-bots/freight_broker",
    tier: "Growth",
    category: "freight",
    status: "active",
    phase: "growth",
    order: 7,
    features: ["Shipments", "Rates", "Carrier Matching", "Tracking"],
    aliases: ["freight", "freightbroker", "ai_freight_broker"],
  },
  {
    id: 8,
    key: "safety_manager_bot",
    name: "AI Safety Manager",
    description: "Monitors safety data, incident reporting, and compliance checks",
    icon: "🛡️",
    path: "/ai-bots/safety/dashboard",
    tier: "Professional",
    category: "safety",
    status: "active",
    phase: "professional",
    order: 8,
    features: ["Incident Reports", "Audits", "Compliance", "Training"],
    aliases: ["safety_manager", "safety_manager_bot", "safety"],
  },
  {
    id: 9,
    key: "intelligence_bot",
    name: "AI Intelligence Bot",
    description: "Strategic analysis, executive insights, and reporting",
    icon: "🧠",
    path: "/ai-bots/control?bot=intelligence_bot",
    tier: "Professional",
    category: "intelligence",
    status: "active",
    phase: "professional",
    order: 9,
    features: ["KPIs", "Market Analysis", "Performance Metrics", "Forecasts"],
    aliases: ["intelligence", "market_intelligence"],
  },
  {
    id: 10,
    key: "mapleload_bot",
    name: "AI MapleLoad Canada",
    description: "Canadian logistics intelligence and cross-border coordination",
    icon: "🍁",
    path: "/ai-bots/mapleload-canada",
    tier: "Professional",
    category: "international",
    status: "active",
    phase: "professional",
    order: 10,
    features: ["Market Signals", "Cross-Border", "Carrier Network", "Routes"],
    aliases: ["mapleload", "mapleload_canada"],
  },
  {
    id: 11,
    key: "general_manager",
    name: "AI General Manager",
    description: "Executive oversight and strategic reporting",
    icon: "👔",
    path: "/ai-bots/general-manager",
    tier: "Enterprise",
    category: "management",
    status: "active",
    phase: "enterprise",
    order: 11,
    features: ["Dashboard", "Reports", "Analytics", "Strategic Planning"],
  },
  {
    id: 12,
    key: "finance_bot",
    name: "AI Finance Bot",
    description: "Financial analysis, revenue tracking, expense management, and invoice processing",
    icon: "💰",
    path: "/ai-bots/finance",
    tier: "Enterprise",
    category: "finance",
    status: "active",
    phase: "enterprise",
    order: 12,
    features: ["Financial Analysis", "Expense Tracking", "Revenue Reports", "Budget Planning", "Invoicing"],
    aliases: ["finance_bot", "bot_finance", "finance"],
  },
  {
    id: 13,
    key: "legal_consultant",
    name: "AI Legal Consultant",
    description: "Reviews legal documents and ensures compliance",
    icon: "⚖️",
    path: "/ai-bots/legal",
    tier: "Enterprise",
    category: "legal",
    status: "active",
    phase: "enterprise",
    order: 13,
    features: ["Contract Review", "Compliance", "Risk Flags", "Reports"],
    aliases: ["legal_consultant", "legal_bot", "legal"],
  },
  {
    id: 14,
    key: "security_manager_bot",
    name: "AI Security Manager",
    description: "Security monitoring, threat detection, and compliance auditing",
    icon: "🔒",
    path: "/ai-bots/security_manager",
    tier: "Enterprise",
    category: "security",
    status: "active",
    phase: "enterprise",
    order: 14,
    features: ["Monitoring", "Threat Detection", "Audit Logs", "Access Control"],
    aliases: ["security_manager", "security"],
  },
  {
    id: 15,
    key: "system_manager_bot",
    name: "AI System Manager",
    description: "System performance, infrastructure health, and optimization",
    icon: "🖥️",
    path: "/ai-bots/system-admin",
    tier: "Enterprise",
    category: "infrastructure",
    status: "active",
    phase: "enterprise",
    order: 15,
    features: ["System Status", "Resource Use", "Optimization", "Alerts"],
    aliases: ["system_manager", "system_admin", "system_bot"],
  },
  {
    id: 16,
    key: "maintenance_dev",
    name: "AI Maintenance Dev",
    description: "Monitors bot health, fixes bugs, and suggests system upgrades",
    icon: "🔧",
    path: "/ai-bots/maintenance-dashboard",
    tier: "Enterprise",
    category: "maintenance",
    status: "active",
    phase: "enterprise",
    order: 16,
    features: ["Health Checks", "Diagnostics", "Fixes", "Performance"],
    aliases: ["dev_maintenance", "maintenance_dev_bot", "maintenance"],
  },
  {
    id: 17,
    key: "marketing_manager",
    name: "AI Marketing Manager",
    description: "Campaign orchestration, lead nurturing, and marketing performance insights",
    icon: "MKT",
    path: "/admin/ai/marketing-bot",
    tier: "Marketing",
    category: "marketing",
    status: "active",
    phase: "specialized",
    order: 17,
    features: ["Campaigns", "Leads", "Analytics", "ROI Tracking"],
    aliases: ["marketing_bot", "marketing_manager_bot"],
  },
  {
    id: 18,
    key: "partner_manager",
    name: "AI Partner Manager",
    description: "Partner operations and alliance workflows",
    icon: "PRT",
    path: "/ai-bots/partner-management",
    tier: "Management",
    category: "partners",
    status: "active",
    phase: "specialized",
    order: 18,
    features: ["Partner Onboarding", "Commission Tracking", "Performance Reports"],
    aliases: ["partner_management", "partner"],
  },
  {
    id: 19,
    key: "trainer_bot",
    name: "AI Trainer Bot",
    description: "Training and simulation orchestration for bot readiness before production rollout",
    icon: "TRN",
    path: "/ai-bots/trainer",
    tier: "Training",
    category: "training",
    status: "active",
    phase: "specialized",
    order: 19,
    features: ["Simulations", "Training Data", "Performance Metrics", "Certification"],
    aliases: ["trainer", "training_bot"],
  },
  {
    id: 20,
    key: "payment_bot",
    name: "Payment Gateway Dashboard",
    description: "Secure payment processing, invoice management, transaction tracking, and finance bot integration",
    icon: "💳",
    path: "/ai-bots/payment",
    tier: "Enterprise",
    category: "finance",
    status: "active",
    phase: "enterprise",
    order: 21,
    features: [
      "Secure Payments",
      "Invoice Management",
      "Transaction History",
      "Refund Processing",
      "Webhook Integration",
      "Multi-currency Support",
      "Finance Bot Integration",
      "Real-time Analytics",
    ],
    aliases: ["payment_bot", "payment-gateway", "payment", "stripe", "payment_gateway"],
  },
];

export const getBotsByTier = (tier, { includeInactive = true } = {}) =>
  BOTS_REGISTRY.filter((bot) => bot.tier === tier && (includeInactive || bot.status === "active"));

export const getAvailableTiers = () =>
  TIER_ORDER.filter((tier) => BOTS_REGISTRY.some((bot) => bot.tier === tier));

export const searchBots = (query) => {
  const needle = String(query || "").trim().toLowerCase();
  if (!needle) return BOTS_REGISTRY;

  return BOTS_REGISTRY.filter((bot) => {
    const aliases = Array.isArray(bot.aliases) ? bot.aliases : [];
    return (
      bot.name.toLowerCase().includes(needle) ||
      bot.description.toLowerCase().includes(needle) ||
      bot.key.toLowerCase().includes(needle) ||
      aliases.some((alias) => alias.toLowerCase().includes(needle))
    );
  });
};
