export const COUNTRIES = [
  { iso2: "US", name: "United States", callingCode: "+1", flag: "🇺🇸" },
  { iso2: "CA", name: "Canada", callingCode: "+1", flag: "🇨🇦" },
  { iso2: "MX", name: "Mexico", callingCode: "+52", flag: "🇲🇽" },
  { iso2: "GB", name: "United Kingdom", callingCode: "+44", flag: "🇬🇧" },
  { iso2: "IE", name: "Ireland", callingCode: "+353", flag: "🇮🇪" },
  { iso2: "FR", name: "France", callingCode: "+33", flag: "🇫🇷" },
  { iso2: "DE", name: "Germany", callingCode: "+49", flag: "🇩🇪" },
  { iso2: "ES", name: "Spain", callingCode: "+34", flag: "🇪🇸" },
  { iso2: "IT", name: "Italy", callingCode: "+39", flag: "🇮🇹" },
  { iso2: "NL", name: "Netherlands", callingCode: "+31", flag: "🇳🇱" },
  { iso2: "BE", name: "Belgium", callingCode: "+32", flag: "🇧🇪" },
  { iso2: "CH", name: "Switzerland", callingCode: "+41", flag: "🇨🇭" },
  { iso2: "SE", name: "Sweden", callingCode: "+46", flag: "🇸🇪" },
  { iso2: "NO", name: "Norway", callingCode: "+47", flag: "🇳🇴" },
  { iso2: "DK", name: "Denmark", callingCode: "+45", flag: "🇩🇰" },
  { iso2: "TR", name: "Turkey", callingCode: "+90", flag: "🇹🇷" },
  { iso2: "RU", name: "Russia", callingCode: "+7", flag: "🇷🇺" },
  { iso2: "IN", name: "India", callingCode: "+91", flag: "🇮🇳" },
  { iso2: "PK", name: "Pakistan", callingCode: "+92", flag: "🇵🇰" },
  { iso2: "BD", name: "Bangladesh", callingCode: "+880", flag: "🇧🇩" },
  { iso2: "CN", name: "China", callingCode: "+86", flag: "🇨🇳" },
  { iso2: "JP", name: "Japan", callingCode: "+81", flag: "🇯🇵" },
  { iso2: "KR", name: "South Korea", callingCode: "+82", flag: "🇰🇷" },
  { iso2: "SG", name: "Singapore", callingCode: "+65", flag: "🇸🇬" },
  { iso2: "AU", name: "Australia", callingCode: "+61", flag: "🇦🇺" },
  { iso2: "NZ", name: "New Zealand", callingCode: "+64", flag: "🇳🇿" },
  { iso2: "SA", name: "Saudi Arabia", callingCode: "+966", flag: "🇸🇦" },
  { iso2: "AE", name: "United Arab Emirates", callingCode: "+971", flag: "🇦🇪" },
  { iso2: "QA", name: "Qatar", callingCode: "+974", flag: "🇶🇦" },
  { iso2: "KW", name: "Kuwait", callingCode: "+965", flag: "🇰🇼" },
  { iso2: "OM", name: "Oman", callingCode: "+968", flag: "🇴🇲" },
  { iso2: "BH", name: "Bahrain", callingCode: "+973", flag: "🇧🇭" },
  { iso2: "EG", name: "Egypt", callingCode: "+20", flag: "🇪🇬" },
  { iso2: "SD", name: "Sudan", callingCode: "+249", flag: "🇸🇩" },
  { iso2: "ZA", name: "South Africa", callingCode: "+27", flag: "🇿🇦" },
  { iso2: "NG", name: "Nigeria", callingCode: "+234", flag: "🇳🇬" },
  { iso2: "KE", name: "Kenya", callingCode: "+254", flag: "🇰🇪" },
  { iso2: "BR", name: "Brazil", callingCode: "+55", flag: "🇧🇷" },
  { iso2: "AR", name: "Argentina", callingCode: "+54", flag: "🇦🇷" },
  { iso2: "CL", name: "Chile", callingCode: "+56", flag: "🇨🇱" },
];
